//---------------------------------------------------------------------------
#ifndef DebugH
#define DebugH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <ComCtrls.hpp>
#include <Buttons.hpp>
class TSystem;
//---------------------------------------------------------------------------
class TDebugForm : public TForm
{
__published:	// IDE-managed Components
    TPanel *Panel8;
    TPanel *Panel9;
    TPanel *Panel2;
    TButton *Run;
    TButton *Step;
    TButton *Stop;
    TButton *Reset;
    TButton *Trace;
    TPanel *Panel6;
    TLabel *Label15;
    TCheckBox *CbWrite;
    TEdit *Break3;
    TEdit *WriteValue;
    TPanel *Panel5;
    TLabel *Label13;
    TCheckBox *CbRead;
    TEdit *Break2;
    TEdit *ReadValue;
    TPanel *Panel4;
    TLabel *Label12;
    TCheckBox *CbExecute;
    TEdit *Break1;
    TListBox *Code;
    TCheckBox *OnChange;
    TPageControl *Registers;
    TTabSheet *m6809;
    TTabSheet *m6800;
    TLabel *Label19;
    TEdit *M6809_PC;
    TLabel *Label1;
    TEdit *M6809_A;
    TLabel *Label2;
    TEdit *M6809_B;
    TLabel *Label10;
    TEdit *Pagelatch;
    TEdit *M6809_D;
    TLabel *Label3;
    TLabel *Label4;
    TEdit *M6809_X;
    TLabel *Label6;
    TEdit *M6809_U;
    TEdit *M6809_S;
    TLabel *Label7;
    TLabel *Label5;
    TEdit *M6809_Y;
    TLabel *Label9;
    TEdit *M6809_flags;
    TLabel *Label11;
    TLabel *Label14;
    TEdit *MPU4_mux;
    TLabel *Label8;
    TEdit *M6809_DP;
    TLabel *Label16;
    TEdit *M6800_PC;
    TLabel *Label20;
    TEdit *M6800_A;
    TLabel *Label21;
    TEdit *M6800_B;
    TEdit *M6800_D;
    TEdit *M6800_X;
    TEdit *M6800_S;
    TLabel *Label30;
    TLabel *Label32;
    TLabel *Label33;
    TLabel *Label34;
    TEdit *M6800_flags;
    TLabel *Label35;
    TLabel *Label36;
    TEdit *MPU3_mux;
    TPanel *Panel1;
    TListBox *Data;
    TLabel *Label17;
    TEdit *MemAddress;
    TButton *Write;
    TEdit *Value;
    TLabel *Label28;
    TEdit *CodeAddress;
    TCheckBox *Update;
    TCheckBox *CatchErrors;
    TTimer *Timer1;
    TRadioButton *ByteWise;
    TRadioButton *WordWise;
    TEdit *WriteAddress;
    TEdit *Waddr;
    TEdit *Wvalue;
    TEdit *Raddr;
    TEdit *Rvalue;
    TRadioButton *DWordWise;
    TButton *FastStep;
    TTimer *Timer2;
    TEdit *ReadCount;
    TSpeedButton *ClearRead;
    TEdit *WriteCount;
    TSpeedButton *ClearWrite;
    TTabSheet *m68000;
    TEdit *M68000PC;
    TEdit *M68000D0;
    TEdit *M68000D1;
    TEdit *M68000D2;
    TEdit *M68000D3;
    TEdit *M68000D4;
    TEdit *M68000D5;
    TEdit *M68000D6;
    TEdit *M68000D7;
    TLabel *Label54;
    TLabel *Label55;
    TLabel *Label56;
    TLabel *Label57;
    TLabel *Label58;
    TLabel *Label59;
    TLabel *Label60;
    TLabel *Label61;
    TLabel *Label62;
    TEdit *M68000SCR;
    TLabel *Label63;
    TEdit *M68000CCR;
    TLabel *Label64;
    TEdit *M68000A0;
    TLabel *Label65;
    TLabel *Label66;
    TLabel *Label67;
    TLabel *Label68;
    TLabel *Label69;
    TLabel *Label70;
    TLabel *Label71;
    TLabel *Label72;
    TEdit *M68000A7;
    TEdit *M68000A6;
    TEdit *M68000A5;
    TEdit *M68000A4;
    TEdit *M68000A3;
    TEdit *M68000A2;
    TEdit *M68000A1;
    TLabel *Label73;
    TEdit *M68000SFC;
    TLabel *Label74;
    TEdit *M68000DFC;
    TScrollBar *ScrollBar1;
    TCheckBox *Traceon;
    TEdit *Cycles;
    TLabel *Label83;
    TSpeedButton *ClearCycles;
  TTabSheet *tms9995;
  TLabel *Label104;
  TEdit *TMS9995_PC;
  TLabel *Label105;
  TEdit *TMS9995_R0;
  TLabel *Label106;
  TEdit *TMS9995_R1;
  TLabel *Label107;
  TEdit *TMS9995_R2;
  TLabel *Label108;
  TLabel *Label109;
  TLabel *Label110;
  TLabel *Label111;
  TLabel *Label112;
  TEdit *TMS9995_R7;
  TEdit *TMS9995_R6;
  TEdit *TMS9995_R5;
  TEdit *TMS9995_R4;
  TEdit *TMS9995_R3;
  TLabel *Label113;
  TLabel *Label114;
  TLabel *Label115;
  TLabel *Label116;
  TLabel *Label117;
  TLabel *Label118;
  TLabel *Label119;
  TLabel *Label120;
  TLabel *Label121;
  TEdit *TMS9995_R15;
  TEdit *TMS9995_R14;
  TEdit *TMS9995_R13;
  TEdit *TMS9995_R12;
  TEdit *TMS9995_R11;
  TEdit *TMS9995_R10;
  TEdit *TMS9995_R9;
  TEdit *TMS9995_R8;
  TEdit *TMS9995_WP;
  TLabel *Label122;
  TEdit *ST;
  TLabel *Label123;
  TLabel *Label124;
  TLabel *Label125;
  TLabel *Label126;
  TLabel *Label127;
  TEdit *DuartTimer1;
  TEdit *DuartTimer2;
  TEdit *Count1;
  TEdit *Count2;
  TLabel *Label128;
  TEdit *Dec;
  TTabSheet *Z80;
  TLabel *Label129;
  TEdit *Z80_PC;
  TLabel *Label130;
  TEdit *Z80_AF;
  TLabel *Label131;
  TEdit *Z80_BC;
  TLabel *Label132;
  TEdit *Z80_DE;
  TLabel *Label133;
  TEdit *Z80_HL;
  TLabel *Label134;
  TEdit *Z80_IX;
  TEdit *Z80_IY;
  TLabel *Label135;
  TLabel *Label136;
  TEdit *Z80_SP;
  TLabel *Label137;
  TEdit *Z80_I;
  TEdit *Z80_IM;
  TLabel *Label138;
  TLabel *Label139;
  TEdit *Z80_AHL;
  TEdit *Z80_ADE;
  TLabel *Label140;
  TLabel *Label141;
  TEdit *Z80_ABC;
  TEdit *Z80_AAF;
  TLabel *Label142;
  TLabel *Label143;
  TEdit *Z80_FLAGS;
  TLabel *Label144;
    TEdit *Pending1;
    TEdit *Pending2;
    TLabel *Label145;
    TEdit *Speed;
    TLabel *Label146;
    TLabel *Label147;
    TLabel *Label148;
        TEdit *Z80CTC_Cnt1;
        TEdit *Z80CTC_Cnt2;
        TEdit *Z80CTC_Cnt3;
        TEdit *Z80CTC_Cnt4;
        TEdit *Z80CTC_Const1;
        TEdit *Z80CTC_Const2;
        TEdit *Z80CTC_Const3;
        TEdit *Z80CTC_Const4;
    TLabel *Label149;
        TEdit *Z80CTC_IState1;
        TEdit *Z80CTC_IState2;
        TEdit *Z80CTC_IState3;
        TEdit *Z80CTC_IState4;
    TLabel *Label150;
        TEdit *Z80CTC_IVector;
    TLabel *Label151;
        TEdit *Z80CTC_NoTimer;
    TTabSheet *m6840;
    TLabel *Label27;
    TLabel *Label75;
    TEdit *PTM_CNT1;
    TEdit *PTM_LAT1;
    TEdit *PTM_LAT2;
    TEdit *PTM_CNT2;
    TEdit *PTM_CNT3;
    TEdit *PTM_LAT3;
    TLabel *Label78;
    TLabel *Label77;
    TLabel *Label76;
    TLabel *Label82;
    TLabel *Label79;
    TLabel *Label80;
    TLabel *Label81;
    TEdit *scnCnt;
    TEdit *PTM_CR3;
    TEdit *PTM_CR2;
    TEdit *PTM_CR1;
    TEdit *PTM_SR;
    TPanel *Panel3;
    TListBox *Stack;
    TCheckBox *locktopc;
    TTabSheet *scn2674;
    TEdit *scnir0;
    TEdit *scnir1;
    TEdit *scnir2;
    TEdit *scnir3;
    TEdit *scnir4;
    TEdit *scnir5;
    TEdit *scnir6;
    TEdit *scnir7;
    TEdit *scnir8;
    TEdit *scnir9;
    TEdit *scnir10;
    TEdit *scnir11;
    TEdit *scnir12;
    TEdit *scnir13;
    TEdit *scnir14;
    TLabel *Label164;
    TLabel *Label165;
    TLabel *Label166;
    TLabel *Label167;
    TLabel *Label168;
    TLabel *Label169;
    TLabel *Label170;
    TLabel *Label171;
    TLabel *Label172;
    TLabel *Label173;
    TLabel *Label174;
    TLabel *Label175;
    TLabel *Label176;
    TLabel *Label177;
    TLabel *Label178;
    TEdit *scnss1;
    TEdit *scnss2;
    TEdit *scnca;
    TLabel *Label179;
    TLabel *Label180;
    TLabel *Label181;
    TEdit *scnirq;
    TEdit *scnstatus;
    TLabel *Label182;
    TLabel *Label183;
    TEdit *scnmask;
    TLabel *Label184;
    TTabSheet *mc6850;
    TEdit *mc6850st;
    TEdit *mc6850ctl;
    TEdit *mc6850tr;
    TEdit *mc6850rc;
    TEdit *mc6850dcd;
    TEdit *mc6850rts;
    TEdit *mc6850cts;
    TLabel *Label185;
    TLabel *Label186;
    TLabel *Label187;
    TLabel *Label188;
    TLabel *Label189;
    TLabel *Label190;
    TLabel *Label191;
    TEdit *Graphics;
    TEdit *Display;
    TLabel *Label192;
    TLabel *Label193;
    TEdit *TrackballIn;
    TEdit *XCount;
    TEdit *YCount;
    TTabSheet *Updates;
    TEdit *SoundUpdates;
    TEdit *AlphaUpdates;
    TEdit *ReelUpdates;
    TEdit *LEDUpdates;
    TEdit *LampUpdates;
    TLabel *Label97;
    TLabel *Label98;
    TLabel *Label100;
    TLabel *Label102;
    TLabel *Label103;
    TLabel *Label18;
    TEdit *CPUUpdates;
    TEdit *Calls;
    TTabSheet *M68681;
    TEdit *isr;
    TEdit *ctlr;
    TEdit *ctur;
    TLabel *Label22;
    TLabel *Label23;
    TLabel *Label24;
    TEdit *imr;
    TLabel *Label25;
    TEdit *ctr;
    TLabel *Label26;
    TEdit *acr;
    TLabel *Label29;
    void __fastcall StopClick(TObject *Sender);
    void __fastcall StepClick(TObject *Sender);
    void __fastcall RunClick(TObject *Sender);
    
    void __fastcall Timer1Timer(TObject *Sender);
    void __fastcall ResetClick(TObject *Sender);
    void __fastcall CodeClick(TObject *Sender);
    void __fastcall CbExecuteClick(TObject *Sender);
    void __fastcall RegChange(TObject *Sender);
    void __fastcall UpdateClick(TObject *Sender);
    void __fastcall BreakChange(TObject *Sender);
    void __fastcall TraceClick(TObject *Sender);

    void __fastcall MemAddressChange(TObject *Sender);
    
    
    void __fastcall WriteClick(TObject *Sender);
    void __fastcall FormShow(TObject *Sender);
    
    void __fastcall CodeAddressChange(TObject *Sender);
    void __fastcall CbReadClick(TObject *Sender);
    void __fastcall CbWriteClick(TObject *Sender);
    void __fastcall Timer2Timer(TObject *Sender);
    void __fastcall FastStepClick(TObject *Sender);
    void __fastcall ClearReadClick(TObject *Sender);
    void __fastcall ClearWriteClick(TObject *Sender);
    void __fastcall CatchErrorsClick(TObject *Sender);
    void __fastcall TraceonClick(TObject *Sender);
    void __fastcall ScrollBar1Change(TObject *Sender);
    void __fastcall ClearCyclesClick(TObject *Sender);
    void __fastcall SpeedButton1Click(TObject *Sender);
    void __fastcall locktopcClick(TObject *Sender);
private:	// User declarations
    bool updating;
    int  offset;
    TSystem *process;
    Arch_Types type;
    int calls;
    void __fastcall StrToHex(String s, unsigned int *addr, unsigned int *mask);
    int __fastcall StrToHex(String s);
    String __fastcall IntToBin(unsigned char value);
public:		// User declarations
    void __fastcall Halt(void);
    void __fastcall Debug_Display(void);
    void __fastcall Display_RAM(void);
    void __fastcall Display_STACK(void);
    void __fastcall SetProcess(TSystem *Process, Arch_Types Type);
    void __fastcall ClearProcess();
    __fastcall TDebugForm(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern TDebugForm *MainDebug;
extern TDebugForm *MatrixDebug;
extern TDebugForm *VideoDebug;
//---------------------------------------------------------------------------
#endif
