/*
 *	machdep.h generated by machdep at Sat Oct  4 14:02:31 1997
 */

#ifndef __machdep_h__
#define __machdep_h__

#ifndef EXIT_SUCCESS
#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1
#endif

#define MACH_SHORT_SIZE 2
#define MACH_INT_SIZE 4
#define MACH_LONG_SIZE 4
#define MACH_FLOAT_SIZE 4
#define MACH_DOUBLE_SIZE 8
#define MACH_BYTE_ORDER_LSB_FIRST
#define MACH_BITFIELDS_LSB_FIRST

typedef unsigned char						UINT8;
typedef unsigned short						UINT16;
typedef unsigned int						UINT32;

typedef char 						INT8;
typedef short						INT16;
typedef int							INT32;

typedef union {
	struct { UINT8 l,h,h2,h3; } b;
	struct { UINT16 l,h; } w;
	UINT32 d;
}	PAIR;

#endif /* __machdep_h__ */
